version: '3.8'

services:
  bot:
    build: .
    container_name: wiki_quiz_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./database:/app/database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
